//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DST__Dükkan_Stok_Takip_.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class GenelAyarlar : global::System.Configuration.ApplicationSettingsBase {
        
        private static GenelAyarlar defaultInstance = ((GenelAyarlar)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GenelAyarlar())));
        
        public static GenelAyarlar Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Ses {
            get {
                return ((int)(this["Ses"]));
            }
            set {
                this["Ses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Yeni_Versiyon_Bildirim {
            get {
                return ((int)(this["Yeni_Versiyon_Bildirim"]));
            }
            set {
                this["Yeni_Versiyon_Bildirim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Mod {
            get {
                return ((int)(this["Mod"]));
            }
            set {
                this["Mod"] = value;
            }
        }
    }
}
