//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DST__Dükkan_Stok_Takip_.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class HesapAyarları : global::System.Configuration.ApplicationSettingsBase {
        
        private static HesapAyarları defaultInstance = ((HesapAyarları)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HesapAyarları())));
        
        public static HesapAyarları Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HDD_NO {
            get {
                return ((string)(this["HDD_NO"]));
            }
            set {
                this["HDD_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SERIAL_KEY {
            get {
                return ((string)(this["SERIAL_KEY"]));
            }
            set {
                this["SERIAL_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LISANS_TURU {
            get {
                return ((string)(this["LISANS_TURU"]));
            }
            set {
                this["LISANS_TURU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SURESI {
            get {
                return ((string)(this["SURESI"]));
            }
            set {
                this["SURESI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0.0.0")]
        public string VERSIYON {
            get {
                return ((string)(this["VERSIYON"]));
            }
            set {
                this["VERSIYON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DST Standard")]
        public string TAM_AD {
            get {
                return ((string)(this["TAM_AD"]));
            }
            set {
                this["TAM_AD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HESAP_ADI {
            get {
                return ((string)(this["HESAP_ADI"]));
            }
            set {
                this["HESAP_ADI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VERİLEN_KEY {
            get {
                return ((string)(this["VERİLEN_KEY"]));
            }
            set {
                this["VERİLEN_KEY"] = value;
            }
        }
    }
}
