//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DST__Dükkan_Stok_Takip_.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class MuhasebeAyarlari : global::System.Configuration.ApplicationSettingsBase {
        
        private static MuhasebeAyarlari defaultInstance = ((MuhasebeAyarlari)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MuhasebeAyarlari())));
        
        public static MuhasebeAyarlari Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Maas_Odeme_Gunu {
            get {
                return ((int)(this["Maas_Odeme_Gunu"]));
            }
            set {
                this["Maas_Odeme_Gunu"] = value;
            }
        }
    }
}
