//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DST__Dükkan_Stok_Takip_.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class YedeklemeAyarlari : global::System.Configuration.ApplicationSettingsBase {
        
        private static YedeklemeAyarlari defaultInstance = ((YedeklemeAyarlari)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new YedeklemeAyarlari())));
        
        public static YedeklemeAyarlari Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Mail {
            get {
                return ((string)(this["Mail"]));
            }
            set {
                this["Mail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Periyod_Turu {
            get {
                return ((int)(this["Periyod_Turu"]));
            }
            set {
                this["Periyod_Turu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Hedef_Zaman {
            get {
                return ((int)(this["Hedef_Zaman"]));
            }
            set {
                this["Hedef_Zaman"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Durum {
            get {
                return ((int)(this["Durum"]));
            }
            set {
                this["Durum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Durum_Zaman_Asimi {
            get {
                return ((int)(this["Durum_Zaman_Asimi"]));
            }
            set {
                this["Durum_Zaman_Asimi"] = value;
            }
        }
    }
}
